# Generated by Django 4.1 on 2022-09-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_text', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='Date published')),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=500)),
                ('likes', models.IntegerField(default=0)),
                ('related_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyblog.article')),
            ],
        ),
    ]
